### ISSUE TITLE
[BUG] Important: We managed to compile/package intel/llvm for nix, yet can't load Lunar Lake GPU/NPU

### ISSUE THREAD

**Issue by izelnakri** [intel/llvm#19751]
### Describe the bug

Hi there,

I'm posting this issue request here because we just discovered it is probably `intel/llvm` / compiler related. Previously it was here: https://github.com/oneapi-src/level-zero/issues/367

After many issues, some assistance from intel engineers and fixes over the last 2 months, we managed to get `intel/llvm` compile/packaged for nix!!

The whole effort was like boiling the ocean almost, the complexity here is massive and @blenderfreaky should get most of the credit getting this to work, please review/contribute and open PRs here if we got any of the knobs wrong/not working or could define it better:  https://github.com/blenderfreaky/intel-nix

In order to test this given this `test.cpp`: 

```cpp
#include <sycl/sycl.hpp>
#include <iostream>
#include <vector>

int main() {
    try {
        sycl::queue queue(sycl::gpu_selector_v);
        std::cout << "Running on device: " << queue.get_device().get_info<sycl::info::device::name>() << std::endl;

        // The size of the data. A larger size will result in more work per kernel.
        const size_t data_size = 1024 * 1024 * 100;

        std::vector<float> data(data_size);
        for (size_t i = 0; i < data_size; ++i) {
            data[i] = static_cast<float>(i);
        }

        sycl::buffer<float, 1> data_buffer(data.data(), sycl::range<1>(data_size));

        // Submit the kernel multiple times to create a sustained load.
        const int iterations = 2048;
        std::cout << "Submitting " << iterations << " iterations of the kernel to generate load..." << std::endl;

        for (int i = 0; i < iterations; ++i) {
            queue.submit([&](sycl::handler& cgh) {
                auto acc = data_buffer.get_access<sycl::access::mode::read_write>(cgh);

                cgh.parallel_for(sycl::range<1>(data_size), [=](sycl::id<1> idx) {
                    acc[idx] = sycl::pow(acc[idx], 1.0001f) * 0.9999f;
                });
            });
        }

        // Wait for all submitted kernels in the queue to complete.
        queue.wait_and_throw();

        std::cout << "Computation finished." << std::endl;

    } catch (const sycl::exception& e) {
        std::cerr << "SYCL exception caught: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

I can compile it on my Lunar Lake laptop:

```zsh
11:50:15 izelnakri ~/Github/intel-nix -> main nix develop
warning: Git tree '/home/izelnakri/Github/intel-nix' is dirty
dev shell ready: CC=/nix/store/hvflxmdlbp9vr5vgvrasr7why5zhjbp7-intel-llvm-nightly-2025-08-05/bin/clang, CXX=/nix/store/hvflxmdlbp9vr5vgvrasr7why5zhjbp7-intel-llvm-nightly-2025-08-05/bin/clang++
Debug Environments you can try: LIBZE_DEBUG=1 ZE_DEBUG=1 SYCL_UR_TRACE=2
11:50:22 izelnakri ~/Github/intel-nix ❄ -> main echo $CXX
/nix/store/hvflxmdlbp9vr5vgvrasr7why5zhjbp7-intel-llvm-nightly-2025-08-05/bin/clang++
11:50:22 izelnakri ~/Github/intel-nix ❄ -> main $CXX -fsycl test.cpp -o test-sycl
11:50:22 izelnakri ~/Github/intel-nix ❄ -> main ./test-sycl
SYCL exception caught: No device of requested type 'info::device_type::gpu' available.
```

I also run the binary with some debug flags:

```zsh
17:48:22 izelnakri ~/Github/intel-nix ❄ -> main ONEAPI_DEVICE_SELECTOR="level_zero:gpu" SYCL_UR_USE_LEVEL_ZERO_V2=1 LIBZE_DEBUG=1 ZE_DEBUG=1 ./test-sycl

zeInit with flags value of 1

[2025-08-08 17:58:16.203] [ze_loader] [info] Loader Version 1.22.4  - No git SHA found, compiled outside git folder.
[2025-08-08 17:58:16.203] [ze_loader] [trace] Using Loader Library Path:
[2025-08-08 17:58:16.249] [ze_loader] [trace] Loading Driver libze_intel_gpu.so.1 succeeded from: /run/opengl-driver/lib/libze_intel_gpu.so.1
[2025-08-08 17:58:16.249] [ze_loader] [trace] Load Library of libze_intel_gpu_legacy1.so.1 failed with libze_intel_gpu_legacy1.so.1: cannot open shared object file: No such file or directory
[2025-08-08 17:58:16.249] [ze_loader] [trace] Load Library of libze_intel_vpu.so.1 failed with libze_intel_vpu.so.1: cannot open shared object file: No such file or directory
[2025-08-08 17:58:16.249] [ze_loader] [trace] Loading Driver libze_intel_npu.so.1 succeeded from: /run/opengl-driver/lib/libze_intel_npu.so.1
[2025-08-08 17:58:16.249] [ze_loader] [info] Validation Layer Enabled
[2025-08-08 17:58:16.249] [ze_loader] [trace] Load Library of libze_validation_layer.so.1 failed with libze_validation_layer.so.1: cannot open shared object file: No such file or directory
[2025-08-08 17:58:16.249] [ze_loader] [trace] Tracing Layer Library Path: libze_tracing_layer.so.1
[2025-08-08 17:58:16.249] [ze_loader] [trace] Load Library of libze_tracing_layer.so.1 failed with libze_tracing_layer.so.1: cannot open shared object file: No such file or directory
[2025-08-08 17:58:16.249] [ze_loader] [info] Intercept Enabled
[2025-08-08 17:58:16.249] [ze_loader] [info] zeInit succeeded
[2025-08-08 17:58:16.250] [ze_loader] [trace] check_drivers(flags=ZE_INIT_FLAG_GPU_ONLY)
[2025-08-08 17:58:16.260] [ze_loader] [trace] init driver (global ddi) libze_intel_npu.so.1 zeInit(ZE_INIT_FLAG_GPU_ONLY) returning ZE_RESULT_ERROR_UNINITIALIZED

Level Zero Loader Version: 1.22.4


zeInitDrivers with flags value of 1

[2025-08-08 17:58:16.260] [ze_loader] [trace] check_drivers(desc->flags=|ZE_INIT_DRIVER_TYPE_FLAG_GPU|)
[2025-08-08 17:58:16.260] [ze_loader] [trace] driverSorting libze_intel_gpu.so.1 using zeInitDrivers(|ZE_INIT_DRIVER_TYPE_FLAG_GPU||ZE_INIT_DRIVER_TYPE_FLAG_NPU|)
[2025-08-08 17:58:16.260] [ze_loader] [trace] driverSorting libze_intel_npu.so.1 using zeInitDrivers(|ZE_INIT_DRIVER_TYPE_FLAG_GPU||ZE_INIT_DRIVER_TYPE_FLAG_NPU|)
[2025-08-08 17:58:16.262] [ze_loader] [trace] Drivers after sorting:
Driver Type: 2 Driver Name: libze_intel_gpu.so.1
Driver Type: 4 Driver Name: libze_intel_npu.so.1
[2025-08-08 17:58:16.262] [ze_loader] [trace] init driver (global ddi) libze_intel_npu.so.1 zeInitDrivers(|ZE_INIT_DRIVER_TYPE_FLAG_GPU|) returning ZE_RESULT_ERROR_UNINITIALIZED
Skipping L0 V1 adapter: Specific adapter version requested by UR_LOADER_USE_LEVEL_ZERO_V2 or SYCL_UR_USE_LEVEL_ZERO_V2

zeInit with flags value of 1


Level Zero Loader Version: 1.22.4


zeInitDrivers with flags value of 1


zesInit with flags value of 0

[2025-08-08 17:58:16.262] [ze_loader] [trace] check_drivers(flags=0(ZE_INIT_ALL_DRIVER_TYPES_ENABLED))
[2025-08-08 17:58:16.265] [ze_loader] [trace] init driver libze_intel_gpu.so.1 zesInit(0(ZE_INIT_ALL_DRIVER_TYPES_ENABLED)) returning ZE_RESULT_SUCCESS
[2025-08-08 17:58:16.265] [ze_loader] [trace] init driver libze_intel_npu.so.1 zesInit(0(ZE_INIT_ALL_DRIVER_TYPES_ENABLED)) returning ZE_RESULT_SUCCESS

1 L0 Drivers found.

[2025-08-08 17:58:16.265] [ze_loader] [trace] driverSorting libze_intel_gpu.so.1 failed, zeInit returned ZE_RESULT_SUCCESS
[2025-08-08 17:58:16.265] [ze_loader] [trace] driverSorting libze_intel_npu.so.1 failed, zeInit returned ZE_RESULT_SUCCESS
[2025-08-08 17:58:16.265] [ze_loader] [trace] Drivers after sorting:
Driver Type: 2147483647 Driver Name: libze_intel_gpu.so.1
Driver Type: 2147483647 Driver Name: libze_intel_npu.so.1
NOTE: Number of queue groups = 2
NOTE: main blitter/copy engine is available
NOTE: link blitter/copy engines are not available
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x2106ae0, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x2106ae0, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x2106ae0, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x2106ae0, inOrder: 1
ze_event_pool_desc_t flags set to: 1
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x2106ae0, inOrder: 1
Abort was called at 42 line in file:
/build/source/shared/source/built_ins/built_ins.cpp
```

a - I tried all combinations of `ONEAPI_DEVICE_SELECTOR` and `SYCL_DEVICE_FILTER` and none seem to be working.

b - We initially compiled `intel/llvm` project with cmake `UR_BUILD_ADAPTER_L0_V2=false` and the runtime above is adapter v2, could that be the problem? We need better documentation on *all* Intel AI Stack software build knobs, there are just too many and its very difficult for us to get this right without any intel engineer review or assistance. 

My Lunar Lake CPU: Intel Ultra 7 258V (8) @ 4.800GHz
My Lunar Lake Integrated GPU: Intel Arc Graphics 130V / 140V]

The process gets loaded on the GPU for a second, I can see it on `gputop`, this time I use https://github.com/intel/llvm/tree/47f90e6099d53b54846937e406aa92c710d3ce75 which seems to be passing on llvm CI side @aelovikov-intel, @sarnex), but please let us know if there is anything else we can do. 

Thank you for your consideration and past/future assistance!

P.S I'm able to run `whisper.cpp` on my GPU with `OneAPI Toolkit 2025.2`, with our nix package I can compile it but it cant run on my GPU neither, only on my CPU.

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- NixOS (Please try this in full distribution or in a VM setting).

**Comment by sarnex** [comment]
At first look this definitely seems like an issue with the GPU driver setup.

Are you using all correct versions of the GPU stack? Here is the list for the current version used in CI here 
[compute-runtime](https://github.com/intel/compute-runtime/releases/tag/25.27.34303.5): 25.27.34303.5
level-zero: 1.22.5
intel-graphics-compiler: 2.14.1
igsc: 0.9.5

**Comment by izelnakri** [comment]
@sarnex I highly doubt it, because (assuming it hits the same drivers), I can compile `test.cpp` in a `whisper.cpp` repo which targets  `oneAPI Toolkit 2025.2` `$CXX` compiler with `export ONEAPI_ROOT="$HOME/intel/oneapi"` and `source "$ONEAPI_ROOT/setvars.sh" --force 2>/dev/null`prior and then run `./test-sycl` correctly.

`source $ONEAPI_ROOT/setvars.sh` probably does too much magic, however there is a high chance we have a problem in the compiler or its runtime, rather than the driver of my laptop, based on my observations/assumptions so far. Maybe each distribution of the compiler requires very specific packages. I can print all my environment specific information and more debug flags, just tell me which commands or what to run ;)

Here is a workflow where `test.cpp` compilation and running works(I suspect it is using the same driver of my laptop, but I dont know):

My whisper.cpp repo flake.nix: 

```nix
# Maybe some minor stuff, redundant here:
{
  description = "Development environment for whisper.cpp with Intel compilers and SYCL";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable"; 
    flake-utils.url = "github:numtide/flake-utils";
    intelNix.url = "path:/home/izelnakri/Github/intel-nix";
    oneDNN.url = "path:/home/izelnakri/Github/oneDNN";
  };

  outputs = { self, nixpkgs, flake-utils, intelNix, oneDNN }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        intelLLVM = intelNix.outputs.packages.${system}.src;
        sycl = intelLLVM.oneMath-sycl-blas;
        myOneDNN = intelLLVM.oneDNN;
        FHSTargetPkgs = with pkgs; [ # NOTE: Most of these were needed for $ whisper-stream rather than ./test-sycl
          glibc.dev # NOTE: Required: #include <stdio.h>
          gcc-unwrapped # NOTE: essential! for pass binutils-2.44/bin/ld: cannot find crtbegin.o: No such file or directory

          zlib # NOTE: loading shared libraries: libz.so

          level-zero  # NOTE: Required: Intel GPU driver interface, Unified runtime!
          SDL2 # NOTE: Required dependency
          openvino # NOTE: Required dependency
          llvmPackages.openmp

          sycl
          myOneDNN
        ];

        fhsEnv = pkgs.buildFHSEnv rec {
          name = "whisper-cpp-dev";
          
          targetPkgs = pkgs: (with pkgs; FHSTargetPkgs);
          
          profile = ''
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8
            # I comment this out when I test ours:
            export ONEAPI_ROOT="$HOME/intel/oneapi" # Intel compiler paths (adjust these to your installation)
            
            # REQUIRED: Setup OpenVINO after setting up basic environment:
            source ${pkgs.openvino}/setupvars.sh 2>/dev/null || echo "OpenVINO setup completed with warnings"
            # REQUIRED: Makes icx & icpx available in the $PATH and more, I comment this out when I test ours
            source "$ONEAPI_ROOT/setvars.sh" --force 2>/dev/null
            
            export CC=icx
            export CXX=icpx
            # export CC="${intelLLVM.llvm}/bin/clang"
            # export CXX="${intelLLVM.llvm}/bin/clang++"

            echo "🚀 Entering whisper.cpp development environment with Intel compilers"
            echo "📍 Intel OneAPI root: $ONEAPI_ROOT"
            echo "🔧 CC=$CC, CXX=$CXX"
            echo "TO rebuild:"
            echo "rm -rf build && cmake -B build -DWHISPER_SDL2=ON -DWHISPER_OPENVINO=1 -DGGML_SYCL=ON -DCMAKE_C_COMPILER=\$CC -DCMAKE_CXX_COMPILER=\$CXX"
            echo "cmake --build build -j --config Release"
            echo "./build/bin/whisper-stream -m ./models/ggml-base.en.bin -t 8 --step 500 --length 5000"

            export ZDOTDIR=$(mktemp -d)
            cat > "$ZDOTDIR/.zshrc" << 'EOF'
              source ~/.zshrc # Source the original .zshrc, required.

              # NOTE: Only way to source/execute zsh code after sourcing ~/.zshrc:
              function parse_git_branch {
                git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ ->\ \1/'
              }

              function display_jobs_count_if_needed {
                local job_count=$(jobs -s | wc -l | tr -d " ")

                if [ $job_count -gt 0 ]; then
                  echo "%B%F{yellow}%j| ";
                fi
              }

              PROMPT="%F{blue}$(date +%H:%M:%S) $(display_jobs_count_if_needed)%B%F{green}%n %F{blue}%~%F{cyan} ❄%F{yellow}$(parse_git_branch) %f%{$reset_color%}"

              echo ""
            EOF

            exec zsh -i
          '';
        };
      in
      {
        devShells.default = pkgs.mkShell rec {
          name = "whisper-cpp-fhs-dev";

          buildInputs = FHSTargetPkgs ++ [ fhsEnv ]; # NOTE: pkgs here & FSH Environment absolute necessary for the Intel DPC++ Compiler for now!

          hardeningDisable = [ "zerocallusedregs" ]; # NOTE: Probably shouldnt be needed
          shellHook = ''
            echo "🔄 Setting up FHS environment for whisper.cpp development..."
            echo "🏗️ This will provide a standard Linux environment for Intel compilers"
            echo "🚀 Auto-entering FHS environment..."

            exec whisper-cpp-dev # Auto-enters FHS environment, normally in nix we dont need FHS environment
          ''; # Shell hook that runs before entering FHS
        };
        

        # NOTE: In future, smt like this will allow: $ nix run github:izelnakri/whisper.cpp -- -first-flag --second-flag=true --foo='bar'
        #   packages.default = intelLLVM.llvm.stdenv.mkDerivation rec {
        #     name = "whisper.cpp";
        #     src = ./.;
        #
        #     buildInputs = with pkgs; [
        #       cmake
        #       zlib # NOTE: loading shared libraries: libz.so
        #
        #       level-zero  # NOTE: Required: Intel GPU driver interface, Unified runtime!
        #       SDL2 # NOTE: Required dependency
        #       openvino # NOTE: Required dependency
        #       llvmPackages.openmp
        #
        #       sycl
        #       myOneDNN
        #     ];
        #
        #     cmakeFlags = [
        #       "-DWHISPER_SDL2=ON"
        #       "-DWHISPER_OPENVINO=1"
        #       "-DGGML_SYCL=ON"
        #     ];
        #   };
      });
}
```

Then I run everything on `icpx`:


```zsh
09:56:57 izelnakri ~/Github/whisper.cpp -> master nix develop
warning: Git tree '/home/izelnakri/Github/whisper.cpp' is dirty
🔄 Setting up FHS environment for whisper.cpp development...
🏗️ This will provide a standard Linux environment for Intel compilers
🚀 Auto-entering FHS environment...
[setupvars.sh] WARNING: Can not find OpenVINO Python binaries by path /nix/store/qpiwykvr4037alxm065j3zk9yjzqc4sx-openvino-2025.2.0/python
[setupvars.sh] WARNING: OpenVINO Python environment does not set properly
[setupvars.sh] OpenVINO environment initialized

:: initializing oneAPI environment ...
   2hwsn5xmqrjdn9nsf4lzlz0s0bbj7fwh-whisper-cpp-dev-init: BASH_VERSION = 5.3.0(1)-release
   args: Using "$@" for setvars.sh arguments: --force
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: ipp -- latest
:: ippcp -- latest
:: mkl -- latest
:: mpi -- latest
:: pti -- latest
:: tbb -- latest
:: umf -- latest
:: vtune -- latest
:: oneAPI environment initialized ::

🚀 Entering whisper.cpp development environment with Intel compilers
📍 Intel OneAPI root: /home/izelnakri/intel/oneapi
🔧 CC=icx, CXX=icpx
TO rebuild:
rm -rf build && cmake -B build -DWHISPER_SDL2=ON -DWHISPER_OPENVINO=1 -DGGML_SYCL=ON -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
cmake --build build -j --config Release
./build/bin/whisper-stream -m ./models/ggml-base.en.bin -t 8 --step 500 --length 5000

09:57:11 izelnakri ~/Github/whisper.cpp ❄ -> master echo $CXX
icpx
09:57:11 izelnakri ~/Github/whisper.cpp ❄ -> master rm ./test-sycl
09:57:11 izelnakri ~/Github/whisper.cpp ❄ -> master $CXX -fsycl test.cpp -o test-sycl
09:57:11 izelnakri ~/Github/whisper.cpp ❄ -> master ./build/bin/whisper-stream -m ./models/ggml-base.en.bin -t 8 --step 500 --length 5000
09:57:11 izelnakri ~/Github/whisper.cpp ❄ -> master ./test-sycl
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
Computation finished.
```

**Comment by izelnakri** [comment]
Hi there,

Here's a detailed report of this bugfix that I think you'll find VERY interesting. @blenderfreaky and I've spent quite a bit of our work hours and all sorts of help & assistance to fix this bug, and I think you'll find this story quite surprising/insightful, because debug logs weren't very helpful in this case, nor updating/reverting my system drivers & libraries.  

Additionally, I had this weird behavior where our `test.cpp` would run correctly on my [FHS Environment](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) (which also took me quite a while and advanced nix hacking work to get it to work) but would fail on `nix develop`, `NixOS` and its variants do not provide FHS Environment for very good reasons when it comes to `reproducability` / `security`. 

I've managed to pinpoint the problem to [FHS Environment](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)  requirement,  by locking everything down to a simple `flake.nix` with two development shells: 

```nix
{
  description = "Development environment for whisper.cpp with Intel compilers and SYCL";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        intelLLVM = self.packages.${system}.src;

        FHSTargetPkgs = with pkgs; [
          # level-zero # NOTE: intelLLVM.llvm already includes it
        ];

        fhsEnv = pkgs.buildFHSEnv rec {
          name = "shell-with-fhs-env";

          targetPkgs = pkgs: (with pkgs; FHSTargetPkgs);

          profile = ''
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8

            export CC="${intelLLVM.llvm}/bin/clang"
            export CXX="${intelLLVM.llvm}/bin/clang++"

            # NOTE: This improves the default nix shell in a very minimal & good way:
            export ZDOTDIR=$(mktemp -d)
            cat > "$ZDOTDIR/.zshrc" << 'EOF'
              source ~/.zshrc # Source the original .zshrc, required.

              # NOTE: Only way to source/execute zsh code after sourcing ~/.zshrc:
              function parse_git_branch {
                git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ ->\ \1/'
              }

              function display_jobs_count_if_needed {
                local job_count=$(jobs -s | wc -l | tr -d " ")

                if [ $job_count -gt 0 ]; then
                  echo "%B%F{yellow}%j| ";
                fi
              }

              PROMPT="%F{blue}$(date +%H:%M:%S) $(display_jobs_count_if_needed)%B%F{green}%n %F{blue}%~%F{cyan} ❄%F{yellow}$(parse_git_branch) %f%{$reset_color%}"

              echo ""
            EOF

            exec zsh -i
          '';
        };
      in
      {
        # $ nix develop
        devShells.default = pkgs.mkShell rec {
          name = "intel-nix-default-devshell";

          buildInputs = FHSTargetPkgs;

          hardeningDisable = [ "zerocallusedregs" ]; # NOTE: Probably shouldnt be needed in future
          shellHook = ''
            export ZDOTDIR=$(mktemp -d)
            cat > "$ZDOTDIR/.zshrc" << 'EOF'
              source ~/.zshrc # Source the original .zshrc, required.

              # NOTE: Only way to source/execute zsh code after sourcing ~/.zshrc:
              function parse_git_branch {
                git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ ->\ \1/'
              }

              function display_jobs_count_if_needed {
                local job_count=$(jobs -s | wc -l | tr -d " ")

                if [ $job_count -gt 0 ]; then
                  echo "%B%F{yellow}%j| ";
                fi
              }

              PROMPT="%F{blue}$(date +%H:%M:%S) $(display_jobs_count_if_needed)%B%F{green}%n %F{blue}%~%F{cyan} ❄%F{yellow}$(parse_git_branch) %f%{$reset_color%}"

              export LANG=C.UTF-8
              export LC_ALL=C.UTF-8
              export CC="${intelLLVM.llvm}/bin/clang"
              export CXX="${intelLLVM.llvm}/bin/clang++"
            EOF

            exec zsh -i
          '';
        };

        # $ nix develop ".#fhs"
        devShells.fhs = pkgs.mkShell rec {
          name = "intel-nix-fhs-devshell";

          buildInputs = FHSTargetPkgs ++ [ fhsEnv ];
          hardeningDisable = [ "zerocallusedregs" ]; # NOTE: Probably shouldnt be needed in future
          shellHook = ''
            exec shell-with-fhs-env # Shell hook that runs before entering FHS
          '';
        };

        packages = {
          src = pkgs.callPackage ./src {};
        };

        # NOTE: In future, smt like this will allow: $ nix run github:izelnakri/whisper.cpp -- -first-flag --second-flag=true --foo='bar'
        #   packages.default = intelLLVM.llvm.stdenv.mkDerivation rec {
        #     name = "whisper.cpp";
        #     src = ./.;
        #
        #     buildInputs = with pkgs; [
        #       cmake
        #     ];
        #
        #     cmakeFlags = [
        #       "-DGGML_SYCL=ON" # NOTE: For whisper.cpp along other flags if/when they are needed
        #     ];
        #   };
      });
}
```

So now, I could compile the `test.cpp` in the ideal (non-FHS) `$ nix develop` environment and then run the output in both environments, even without needing the compiler in `OneAPI Toolkit 2025.2`!! 

Now you can see `nix develop ".#fhs"` passes the tests and `nix develop` fails the test while the warnings weren't very descriptive(yet slightly helpful):

```zsh
08:52:17 izelnakri ~/Github/intel-nix -> main nix develop
warning: Git tree '/home/izelnakri/Github/intel-nix' is dirty
08:52:25 izelnakri ~/Github/intel-nix ❄ -> main echo $CXX
/nix/store/a1259f4bb86kp504ppcaw6gzwlfjnq0y-intel-llvm-nightly-2025-08-05/bin/clang++
08:52:25 izelnakri ~/Github/intel-nix ❄ -> main $CXX test.cpp -fsycl -o ./test-sycl
08:52:25 izelnakri ~/Github/intel-nix ❄ -> main ./test-sycl
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
SYCL exception caught: level_zero backend failed with error: 20 (UR_RESULT_ERROR_DEVICE_LOST)
08:52:25 izelnakri ~/Github/intel-nix ❄ -> main exit
08:53:11 izelnakri ~/Github/intel-nix -> main nix develop ".#fhs"
warning: Git tree '/home/izelnakri/Github/intel-nix' is dirty

08:53:20 izelnakri ~/Github/intel-nix ❄ -> main echo $CXX
/nix/store/a1259f4bb86kp504ppcaw6gzwlfjnq0y-intel-llvm-nightly-2025-08-05/bin/clang++
08:53:20 izelnakri ~/Github/intel-nix ❄ -> main ./test-sycl
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
Computation finished.
08:53:20 izelnakri ~/Github/intel-nix ❄ -> main exit
08:53:48 izelnakri ~/Github/intel-nix -> main nix develop
warning: Git tree '/home/izelnakri/Github/intel-nix' is dirty
08:53:55 izelnakri ~/Github/intel-nix ❄ -> main ONEAPI_DEVICE_SELECTOR=level_zero:gpu ZE_DEBUG=1 ./test-sycl

zeInit with flags value of 1

[2025-08-10 08:54:00.129] [ze_loader] [info] Loader Version 1.22.4  - No git SHA found, compiled outside git folder.
[2025-08-10 08:54:00.129] [ze_loader] [trace] Using Loader Library Path:
[2025-08-10 08:54:00.129] [ze_loader] [trace] DDI Driver Extension Path is Enabled
[2025-08-10 08:54:00.171] [ze_loader] [trace] Loading Driver libze_intel_gpu.so.1 succeeded from: /run/opengl-driver/lib/libze_intel_gpu.so.1
[2025-08-10 08:54:00.171] [ze_loader] [trace] Load Library of libze_intel_gpu_legacy1.so.1 failed with libze_intel_gpu_legacy1.so.1: cannot open shared object file: No such file or directory
[2025-08-10 08:54:00.171] [ze_loader] [trace] Load Library of libze_intel_vpu.so.1 failed with libze_intel_vpu.so.1: cannot open shared object file: No such file or directory
[2025-08-10 08:54:00.171] [ze_loader] [trace] Load Library of libze_intel_npu.so.1 failed with libze_intel_npu.so.1: cannot open shared object file: No such file or directory
[2025-08-10 08:54:00.171] [ze_loader] [info] Validation Layer Enabled
[2025-08-10 08:54:00.171] [ze_loader] [trace] Load Library of libze_validation_layer.so.1 failed with libze_validation_layer.so.1: cannot open shared object file: No such file or directory
[2025-08-10 08:54:00.171] [ze_loader] [trace] Tracing Layer Library Path: libze_tracing_layer.so.1
[2025-08-10 08:54:00.171] [ze_loader] [trace] Load Library of libze_tracing_layer.so.1 failed with libze_tracing_layer.so.1: cannot open shared object file: No such file or directory
[2025-08-10 08:54:00.171] [ze_loader] [info] zeInit succeeded
[2025-08-10 08:54:00.171] [ze_loader] [trace] check_drivers(flags=ZE_INIT_FLAG_GPU_ONLY)

Level Zero Loader Version: 1.22.4


zeInitDrivers with flags value of 1

[2025-08-10 08:54:00.183] [ze_loader] [trace] check_drivers(desc->flags=|ZE_INIT_DRIVER_TYPE_FLAG_GPU|)
Skipping L0 V1 adapter: Using default adapter version based on device IP version

zeInit with flags value of 1


Level Zero Loader Version: 1.22.4


zeInitDrivers with flags value of 1


zesInit with flags value of 0

[2025-08-10 08:54:00.183] [ze_loader] [trace] check_drivers(flags=0(ZE_INIT_ALL_DRIVER_TYPES_ENABLED))
[2025-08-10 08:54:00.185] [ze_loader] [trace] init driver libze_intel_gpu.so.1 zesInit(0(ZE_INIT_ALL_DRIVER_TYPES_ENABLED)) returning ZE_RESULT_SUCCESS

1 L0 Drivers found.

NOTE: Number of queue groups = 2
NOTE: main blitter/copy engine is available
NOTE: link blitter/copy engines are not available
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x22bd528, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x22bd528, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x22bd528, inOrder: 1
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x22bd528, inOrder: 1
ze_event_pool_desc_t flags set to: 1
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
Copy offload is requested but is not supported by the driver.
create command list ordinal: 0, type: immediate, device: 0x22bd528, inOrder: 1
Abort was called at 42 line in file:
/build/source/shared/source/built_ins/built_ins.cpp
zsh: abort (core dumped)  ONEAPI_DEVICE_SELECTOR=level_zero:gpu ZE_DEBUG=1 ./test-sycl
```

I've then checked the `/build/source/shared/source/built_ins/built_ins.cpp` and found that is related to the `device`/driver being null, its been very strange finding because I did have a driver on `/run/opengl-driver`(I removed my NPU driver to further lock-down my environment for bugfix):

```zsh
09:07:18 izelnakri ~/Github/intel-nix ❄ -> main ls -lah /dev/dri
drwxr-xr-x  root root   100 B  Sun Aug 10 08:23:21 2025  .
drwxr-xr-x  root root   4.1 KB Sun Aug 10 08:23:29 2025  ..
drwxr-xr-x  root root    80 B  Sun Aug 10 08:23:21 2025  by-path
crw-rw----+ root video    0 B  Sun Aug 10 08:23:27 2025  card0
crw-rw-rw-  root render   0 B  Sun Aug 10 08:23:21 2025  renderD128
08:53:55 izelnakri ~/Github/intel-nix ❄ -> main ls -lah /run/opengl-driver
lrwxrwxrwx root root 60 B Sun Aug 10 08:23:23 2025  /run/opengl-driver ⇒ /nix/store/xf523qwxw80kac0kgmap3qy7cjci1bm2-graphics-drivers
```

Being able to swap drivers & libraries with NixOS(although not easy), I've updated `level-zero` and `intel-compute-runtime` to latest versions: `v1.24.1` and `v25.27.34303.6` respectively. This didn't help...

I was almost going to give up when I saw this in the `intel-compute-runtime` Release Notes:

> Lunar Lake and Battlemage were tested using Ubuntu 24.04.2 LTS with 6.11.0-1009-intel kernel from intel-graphics PPA.

Reference: https://github.com/intel/compute-runtime/releases/tag/25.27.34303.5

(a) Because `NixOS` doesn't allow downgrading to kernel version `6.11` given Linux kernel `v6.11` reached `End of Life`. Lowest I could downgrade my kernel was `6.12` and I did that. However, this didn't help neither...

Finally I decided to feed all these very explicit specifications I could provide thanks to nix & NixOS to a smart LLM like ChatGPT and after few wrong attention diversion, guesses, debugging and refinement of my prompts I figured this driver lookup assumption could be clarified in NixOS(NixOS makes the least assumptions across all common Linux distributions) by setting the standard `/run/opengl-driver/lib` to `$LD_LIBRARY_PATH` on `nix develop`:

```zsh
# Ensure Intel Level Zero runtime finds all driver libraries
export LD_LIBRARY_PATH="/run/opengl-driver/lib:/run/opengl-driver-32/lib:$LD_LIBRARY_PATH"
```

This fixed the problematic runtime in `nix develop` !!: 

```zsh
09:07:01 izelnakri ~/Github/intel-nix -> main nvim flake.nix
09:07:11 izelnakri ~/Github/intel-nix -> main nix develop
warning: Git tree '/home/izelnakri/Github/intel-nix' is dirty

09:07:18 izelnakri ~/Github/intel-nix ❄ -> main ./test-sycl
Running on device: Intel(R) Arc(TM) Graphics
Submitting 2048 iterations of the kernel to generate load...
Computation finished.
```

(b) We could run this test, along with all other tests provided in `OneAPI` projects per package by booting up a `NixOS VM` inside `nixpkgs` CI, this process is a well established practice in `nixpkgs` packages and will ensure future updates to all `OneAPI` nixpkgs will have the most minimal and rock-solid test infrastructure, especially if `nixpkgs` CI System `OfBorg` could utilize latest consumer GPU/CPU/NPUs. Given the recency of all this technology I doubt we could have this in `nixpkgs` anytime soon, so I would appreciate if you eventually commit to utilize `nix` and `NixOS` more in your build systems, development environments, CI Test infrastructure and software release pipelines. 

[Example NixOS Package Test snippet with potential multiple VMs with custom names nodes.${machineName}](https://github.com/izelnakri/nixpkgs/blob/5a66c15a48038d26f68b3d39acf54fd0558aec71/nixos/tests/bitbox-bridge.nix#L16) . `testScript` is just python, can be run via `nix build ".#nixosTests.bitbox-bridge"`, also `nodes.machine` object is the same `configuration.nix` object `NixOS` uses, so all this is as good as it gets. [Advanced multi VM flake.nix example](https://gist.github.com/izelnakri/bab7c5f6ad66e54d728f4ef280c7d62b)

Nix should improve Intel and UXLFoundation software reliability and adoption significantly since:

- It eliminates the need for build & runtime assumptions.
- Provides the most explicit and cryptographically guaranteed and **secure**(in other words: reproducable) recipes for building software. Better guidance in explicit code for packaging for different(and more) Linux distributions.
- Development & production environment parity for Intel engineers.
- Allows Intel and UXLFoundation project CIs to be more conventional and extensible, less custom for easier onboarding and maintainence.
- Allows better and wider test infrastructure and support guarantees across different versions of Linux kernels.  
- Extremely minimal docker/podman OCI images & container image build pipelines for all consumer computers.
- Enhanced `OneAPI` support or maintainance for NixOS users. 
- New software delivery method for the world: `$ nix run github:intel/llvm -- test.cpp -fsycl -o ./test-sycl` or `nix run github:ollama/ollama -- run gpt-oss` (with intel GPU/NPU support) and/or `$ nix profile install nixpkgs#oneAPIPackages.llvm`
- Prepares Intel and its ecosystem in a better position in this extremely competitive AI Hardware & software ecosystem race.

In an ideal world, if `Intel` and `OneAPI` projects had a `NixOS` based CI, and support commitment to `nixpkgs` packages, we wouldn't have to spend this much of our(mine and @blenderfreaky ) valuable time on these fixes, while `Intel` and `OneAPI` projects could reap all these massive benefits. We hope eventually more Intel engineers will learn and utilize `nix`, despite the steep learning curve, because benefits absolutely outweigh the learning costs. I might be writing code for ~16 years and worked in very prestigious corporations for hardware/software reliability, however I've only learned and been using nix for the last 2-3 years only.

Given we(me and @blenderfreaky) already made significant progress on Intels ideal KPIs above. We are willing to assist Intel on a more professional & temporary/contractual basis to maintain these tools build and release systems. Feel free to reach out to me either on Telegram: @izelnakri or via email if this is of interest to Intel management & development teams.

I think this could be a great investment until we hand over the responsibility to Intel engineers eventually. I think this type of responsibility shouldn't be left to random developers on the internet, especially given how much competency & knowledge this requires ;)

Thanks again for your assistance & interest so far @sarnex @aelovikov-intel @AaronBallman @guy-tamir . Hope to hear from you all, either here or privately for further potential discussion and/or collaboration.

**Comment by sarnex** [comment]
I'm not sure I can comment on the larger question of support for NixOS, but almost all of the issues with NixOS were pretty much directly related to the non-standard file paths, and they could be fixed by setting the standard environment variables, and that seems like it was also the case here (setting `LD_LIBRARY_PATH` fixed it). Since the bug reported here seems solved I'll go ahead and close this, thanks for the in-depth investigation!
